service: arising-serverless
provider:
  name: aws
  runtime: nodejs6.10

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: / # this matches the base path
          method: ANY
          cors: true
      - http:
          path: /{proxy+} # this matches any path
          method: ANY
          cors: true
